name: Update Changelog on Release

on:
  release:
    types: [published]

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment variables
        id: setup-vars
        run: |
          if [ "${{ github.event.release.prerelease }}" = "true" ]; then
            echo "SECTION_TYPE=pre-release" >> $GITHUB_ENV
          else
            echo "SECTION_TYPE=release" >> $GITHUB_ENV
          fi
          RELEASE_DATE="${{ github.event.release.published_at }}"
          [ -z "$RELEASE_DATE" ] && RELEASE_DATE="${{ github.event.release.created_at }}"
          FORMATTED_DATE=$(date -d "$RELEASE_DATE" "+%y-%m-%d")
          echo "FORMATTED_DATE=$FORMATTED_DATE" >> $GITHUB_ENV
          echo "RELEASE_TITLE=${{ github.event.release.name }}" >> $GITHUB_ENV

      - name: Process release body
        id: process-body
        run: |
          echo "${{ github.event.release.body }}" > body.txt
          CONTENT=$(sed -n '/## 新功能/,/---/{//!p}' body.txt | 
            sed 's/^##/###/g' |
            sed 's/（[^）]*）//g' |
            sed '/^$/d')
          echo "processed_content<<EOF" >> $GITHUB_OUTPUT
          echo "$CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Update CHANGELOG.md
        run: |
          {
            echo ""
            echo "## $RELEASE_TITLE $SECTION_TYPE ($FORMATTED_DATE)"
            echo ""
            echo "${{ steps.process-body.outputs.processed_content }}"
          } >> CHANGELOG.md

      - name: Commit changes
        run: |
          git config user.name "PCL-Community-Bot"
          git config user.email "167983016+PCL-Community-Bot@users.noreply.github.com"
          git add CHANGELOG.md
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "docs(CHANGELOG.md): Update changelog for $RELEASE_TITLE"
            git push "https://x-access-token:${{ secrets.BOT }}@github.com/${{ github.repository }}.git" HEAD:main
          fi
